### ISSUE TITLE
[*-apps] We need usage docs for argoconfig and *-apps charts

### ISSUE THREAD

**Issue by hairmare** [adfinis-sygroup/helm-charts#84]
**Affected chart**
All (potential) `*-apps` charts

**Describe the bug**
The auto-generated documentation for the charts is currently lacking. The `examples/` dirs in the charts have proven to not contain enough details for end users.

**Expected behavior**
There should be nice end-user quality docs for `*-apps` charts and the used corresponding library charts.

**Additional context**
The `*-apps` charts aim at being as generic as possible so documenting them in the top-level `docs/` probably makes most sense.

**Tasks**
* [ ] initialize `*-apps` docs
* [ ] explain how to use argoconfig
* [ ] explain app-of-apps concept
* [ ] explain initial deployment & boostrap (esp. regarding `infra-apps` and the `(env-)main-argo` app)
* [ ] document how to use `$app.name` to override namespace based names

**Comment by eyenx** [comment]
@tongpu suggested documenting values like `syncPolicy` inside the `-apps/values.yaml` but I'm against this, as this values come from the `argoconfig` library chart.

How do we want to make sure people know, they can set these values? Extend argoconfig's documentation is enough?

**Comment by hairmare** [comment]
At some we might want to add some high-level docs to the `docs/` folder. Those might describe how to use the app-of-apps things based on argoconfig.

**Comment by hairmare** [comment]
@vmaillot there seem to be several tasks that were not addressed
